Algorithm/urls.py
from django.urls import path

from Algorithm.views import VideoList, DeleteVideo, VideoOutput, BarChartOutput

urlpatterns = [
    path('list_video', VideoList.as_view(), name='list_video'),
    path('video/(?P<pk>\d+)/delete/', DeleteVideo.as_view(), name='delete_video'),
    path('output_video_graph/(?P<pk>\d+)/(?P<is_move_avg>\d+)', VideoOutput, name='output_process'),
    path('graph_output_video/(?P<pk>\d+)', BarChartOutput, name='graph_output_video')
]

SmartCity/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from Algorithm.views import draw_canvas, get_video_input, start_processing, stop_processes, landing_page, VideoLogAPI
from SmartCity import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('draw/(?P<pk>\d+)/', draw_canvas, name='draw_canvas'),
    path('get_video_input', get_video_input, name='get_video_input'),
    path('stop_process/(?P<pk>\d+)/', stop_processes, name="stop_process"),
    path('start_processing/(?P<pk>\d+)/', start_processing, name='start_processing'),
    path('', landing_page, name='landing_page'),
    path('algorithm/', include('Algorithm.urls')),
    path('api/v1/VideoLogData', VideoLogAPI, name='video_log_api')
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Algorithm/models.py
from django.db import models


# Create your models here.
class Videos(models.Model):
    file = models.FileField(null=True, blank=True)
    ip_link = models.TextField(null=True, blank=True)
    line_coord_init_x = models.IntegerField(null=True, blank=True)
    line_coord_init_y = models.IntegerField(null=True, blank=True)
    line_coord_end_x = models.IntegerField(null=True, blank=True)
    line_coord_end_y = models.IntegerField(null=True, blank=True)
    processed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)


class VideoLog(models.Model):
    video = models.ForeignKey('Videos', related_name='Logs', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    moving_avg = models.CharField(max_length=500, null=True, blank=True)
    data = models.CharField(max_length=500, null=True, blank=True)

# class VehicleCount(models.Model):
#     CAR = 0
#     BUS = 1
#     BIKE = 3
#     TRUCK = 4
#     THREE_WHEELER = 5
#     TRACTOR = 6
#
#     VEHICLE_CLASSES = ((CAR, "Car"), (BUS, "Bus"), (BIKE, "Bike"), (TRUCK, "Truck"), (THREE_WHEELER, "Three Wheeler"),
#                        (TRACTOR, "Tractor"))
#     INFLOW = 0
#     OUTFLOW = 1
#     FLOW_CHOICES = ((INFLOW, "Inflow"), (OUTFLOW, "Outflow"))
#     vehicle_id = models.IntegerField()
#     vehicle_type = models.IntegerField(choices=VEHICLE_CLASSES)
#     flow = models.IntegerField(choices=FLOW_CHOICES)
#     video = models.ForeignKey(Videos, related_name='logs', on_delete=models.PROTECT)
#     created_at = models.DateTimeField(auto_now_add=True)
#     updated_at = models.DateTimeField(auto_now=True)

Algorithm/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from Algorithm.models import Videos


class VideoProcessForm(forms.ModelForm):
    class Meta:
        model = Videos
        fields = ['ip_link', 'file']

    def __init__(self, *args, **kwargs):
        super(VideoProcessForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = 'post'
        self.helper.form_action = ''
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.add_input(Submit("submit", "Submit"))

Algorithm/views.py
import json
import os
import time
from queue import PriorityQueue, Queue
from threading import Thread

import cv2
from django.contrib import messages
from django.http import HttpResponse
from django.shortcuts import render, redirect
# Create your views here.
from django.urls import reverse
from django.views.generic import ListView, DeleteView
from pytz import timezone

from Algorithm.forms import VideoProcessForm
from Algorithm.models import Videos, VideoLog
from SmartCity import settings


def landing_page(request):
    return render(request, 'theme/admin/base.html')


def get_video_input(request):
    form = VideoProcessForm()
    if request.method == 'POST':
        form = VideoProcessForm(request.POST, request.FILES)
        if form.is_valid():
            obj = form.save()
            return redirect('draw_canvas', obj.id)
    return render(request, "algorithm/get_video_input.html", {"form": form})


def conversion(initx, inity, endx, endy, frame_width, frame_height):
    """
    Utility Method to convert the co ords in Tkinter to the co ords in image
    :return: Parsed Line Co ordinates
    """
    start_x = round(initx / 900 * frame_width)
    end_x = round(endx / 900 * frame_width)
    start_y = round(inity / 600 * frame_height)
    end_y = round(endy / 600 * frame_height)
    line_coordinate = [start_x, start_y, end_x, end_y]
    return line_coordinate


def draw_canvas(request, pk):
    video = Videos.objects.get(id=pk)
    path = None
    width = 0
    height = 0
    if request.method == "POST":
        data = request.POST
        coords = data.get("value")
        init, end = coords.split("/")
        ix, iy = init.split("|")
        ex, ey = end.split("|")
        if video.file:
            cap = cv2.VideoCapture(video.file.path)
        else:
            if video.ip_link == '0':
                cap = cv2.VideoCapture(0)
            else:
                cap = cv2.VideoCapture(video.ip_link)
        ret, frame = cap.read()
        width = frame.shape[1]
        height = frame.shape[0]
        video.line_coord_init_x, video.line_coord_init_y, video.line_coord_end_x, video.line_coord_end_y = conversion(
            int(ix), int(iy), int(ex), int(ey), width, height)
        video.save()
        cap.release()
        return redirect("list_video")
    else:
        if video.file:
            cap = cv2.VideoCapture(video.file.path)
            ret, frame = cap.read()
            if not os.path.isdir("media/tmp"):
                os.mkdir("media/tmp")
            path = "media/tmp/{}.jpg".format(video.file.name.split(".")[0])
            cv2.imwrite(path, frame)
            cap.release()
        elif video.ip_link:
            if video.ip_link == '0':
                cap = cv2.VideoCapture(0)
            else:
                cap = cv2.VideoCapture(video.ip_link)
            ret, frame = cap.read()
            path = "media/tmp/{}.jpg".format("test")
            cv2.imwrite(path, frame)
    path = "http://" + request.get_host() + "/" + path
    line_coordinates = None
    if video.line_coord_init_x:
        line_coordinates = [video.line_coord_init_x, video.line_coord_init_y, video.line_coord_end_x,
                            video.line_coord_end_y]
    return render(request, "algorithm/template.html",
                  {"image_url": path, "line_coordinates": line_coordinates, 'video_id': pk, 'width': width,
                   'height': height})


def start_processing(request, pk):
    t = Thread(target=initiate_process, args=(pk,))
    t.daemon = True
    t.start()
    messages.success(request, "Processing Started")
    return redirect("list_video")


def initiate_process(pk):
    from traffic_counter import DeepSenseTrafficManagement
    video = Videos.objects.get(id=pk)
    video.processed = True
    video.save()
    line_coordinates = [video.line_coord_init_x, video.line_coord_init_y, video.line_coord_end_x,
                        video.line_coord_end_y]
    path = video.file.path if video.file else video.ip_link
    file = video.file.name if video.file else "IPCAM"
    resultQueue = PriorityQueue()
    bufferQueue = Queue()
    settings.resultQueueDict[pk] = resultQueue
    settings.bufferQueueDict[pk] = bufferQueue
    DeepSenseTrafficManagement(line_coordinates, file, pk, path)


def stop_processes(request, pk):
    video = Videos.objects.get(id=pk)
    video.processed = True
    video.save()
    time.sleep(3)
    video.processed = False
    video.save()
    messages.success(request, "Video Processing Stopped")
    return redirect("list_video")


class VideoList(ListView):
    model = Videos
    template_name = 'algorithm/list_Video.html'


class DeleteVideo(DeleteView):
    model = Videos
    template_name = 'algorithm/delete.html'

    def get_success_url(self):
        return reverse('list_video')


def VideoLogAPI(request):
    video_id = request.GET.get("video_id")
    logs = VideoLog.objects.filter(video_id=video_id).order_by('-created_at')
    is_moving_avg = request.GET.get("is_moving_avg")
    time_gap = request.GET.get("time_gap")
    count = 10
    car_inflow = []
    car_outflow = []
    bike_inflow = []
    bike_outflow = []
    truck_inflow = []
    truck_outflow = []
    ci = 0
    co = 0
    bi = 0
    bo = 0
    ti = 0
    to = 0
    time = []
    t_count = 0
    if is_moving_avg and int(is_moving_avg) == 1:
        logs = logs.filter(moving_avg__isnull=False)
    else:
        logs = logs.filter(moving_avg__isnull=True)
    if time_gap:
        time_gap = int(time_gap)
        count = count * time_gap
    if logs.exists():
        logs = logs[:count]
        asia = timezone("Asia/Kolkata")
        time.append(logs[0].created_at.astimezone(asia).strftime("%H:%M"))
    for log in logs:
        if time_gap:
            if t_count % time_gap == 0 and t_count > 1:
                car_inflow.append(ci)
                car_outflow.append(co)
                bike_inflow.append(bi)
                bike_outflow.append(bo)
                truck_inflow.append(ti)
                truck_outflow.append(to)
                ci = 0
                co = 0
                bi = 0
                bo = 0
                ti = 0
                to = 0
                t_count = 0
                asia = timezone("Asia/Kolkata")
                time.append(log.created_at.astimezone(asia).strftime("%H:%M"))
            else:
                t_count += 1
                temp = json.loads(log.moving_avg)
                ci += temp[0]
                co += temp[3]
                bi += temp[1]
                bo += temp[4]
                ti += temp[2]
                to += temp[5]
        elif is_moving_avg and int(is_moving_avg) == 1:
            temp = json.loads(log.moving_avg)
            car_inflow.append(temp[0])
            car_outflow.append(temp[3])
            bike_inflow.append(temp[1])
            bike_outflow.append(temp[4])
            truck_inflow.append(temp[2])
            truck_outflow.append(temp[5])
            asia = timezone("Asia/Kolkata")
            time.append(log.created_at.astimezone(asia).strftime("%H:%M"))
        else:
            temp = json.loads(log.data)
            car_inflow.append(temp[0])
            car_outflow.append(temp[4])
            bike_inflow.append(temp[1])
            bike_outflow.append(temp[5])
            truck_inflow.append(temp[2])
            truck_outflow.append(temp[6])
            asia = timezone("Asia/Kolkata")
            time.append(log.created_at.astimezone(asia).strftime("%H:%M"))
    car_inflow.reverse()
    car_outflow.reverse()
    bike_inflow.reverse()
    bike_outflow.reverse()
    truck_inflow.reverse()
    truck_outflow.reverse()
    time.reverse()
    if time_gap:
        time.pop()
    data = [car_inflow, car_outflow, bike_inflow, bike_outflow,
            truck_inflow, truck_outflow]
    log = VideoLog.objects.filter(moving_avg__isnull=True, video_id=video_id).order_by('-created_at')
    vehicle_count = []
    if log.exists():
        vehicle_count = log[0].data
    return HttpResponse(json.dumps({"vehicle_count": vehicle_count, "data": {"y": data, "x": time}}))


def VideoOutput(request, pk, is_move_avg):
    return render(request, 'algorithm/output_graph.html',
                  {'video_id': pk, 'is_moving_avg': True if int(is_move_avg) == 1 else False,
                   'update_time': settings.MOVING_AVERAGE_WINDOW})


def BarChartOutput(request,pk):
    return render(request, 'algorithm/grped_bar_chart.html', {'update_time': 300,'video_id':pk})

Algorithm/templates/algorithm/create.html
{% extends 'theme/admin/base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block content_wrapper %}
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel-info panel ">

                    <div class="panel-heading">
                        <h3>Create</h3>
                    </div>
                    <br>
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Algorithm/templates/algorithm/delete.html
{% extends 'theme/admin/base.html' %}
{% block content_wrapper %}
    <div class="container-fluid">
        <div class="center-block h5" >
            <form action="" method="post">
                {% csrf_token %}
                <h5>Are you sure you want to delete "{{ object }}"?</h5>
                <input type="submit" class="btn btn-default" value="Confirm"/>
            </form>
        </div>
    </div>

{% endblock %}

Algorithm/templates/algorithm/get_video_input.html
{% extends 'theme/admin/base.html' %}
{% load crispy_forms_tags %}
{% load staticfiles %}
{% block content_wrapper %}
   <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="panel-info panel ">

                    <div class="panel-heading">
                        <h3>Add Input</h3>
                    </div>
                    <br>
                    {% crispy form %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

Algorithm/templates/algorithm/grped_bar_chart.html
{% extends 'theme/admin/base.html' %}
{% block content_wrapper %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.2/Chart.js"></script>
    <!--<p id="total_count"></p>-->
    <center><h3>Moving Average Bar Graph</h3></center>
    <canvas id="vehicleChart"></canvas>
    <script>
        window.onload = function () {


            var ctx = document.getElementById("vehicleChart").getContext("2d");

            Chart.defaults.global.defaultFontFamily = "Lato";
            Chart.defaults.global.defaultFontSize = 18;
            Chart.defaults.global.defaultFontStyle = "bold";
            var chartOptions = {
                barValueSpacing: 20,
                legend: {
                    display: true,
                    position: 'top',
                    labels: {
                        boxWidth: 80,
                        fontColor: 'black'
                    }
                },
                scales: {
                    yAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'Count',
                            fontSize: 30
                        }
                    }],
                    xAxes: [{
                        scaleLabel: {
                            display: true,
                            labelString: 'Time',
                            fontSize: 30
                        }
                    }]
                }
            };

            myBarChart = new Chart(ctx, {
                type: 'bar',
                options: chartOptions,
            });
            var url = "{% url 'video_log_api' %}?video_id={{ video_id }}&is_moving_avg=1&time_gap=33";
            $.get(url, function (data, status) {
                var data = JSON.parse(data);
                data = data.data;
                console.log(data);
                myBarChart.data = {
                    labels: data.x,
                    datasets: [
                        {
                            label: "Car inflow",
                            backgroundColor: "red",
                            data: data.y[0]
                        },
                        {
                            label: "Car Out Flow",
                            backgroundColor: "blue",
                            data: data.y[1]
                        },
                        {
                            label: "Bike In Flow",
                            backgroundColor: "green",
                            data: data.y[2]
                        },
                        {
                            label: "Bike Out Flow",
                            backgroundColor: "orange",
                            data: data.y[3]
                        },
                        {
                            label: "Truck In Flow",
                            backgroundColor: "brown",
                            data: data.y[4]
                        },
                        {
                            label: "Truck Out Flow",
                            backgroundColor: "black",
                            data: data.y[5]
                        },
                    ]
                };
                myBarChart.update();

            });
            setInterval(function () {
                var url = "{% url 'video_log_api' %}?video_id={{ video_id }}&is_moving_avg=1&time_gap=33";
                $.get(url, function (data, status) {
                    var data = JSON.parse(data);
                    data = data.data;
                    console.log(data.x);
                    myBarChart.data = {
                        labels: data.date,
                        datasets: [
                            {
                                label: "Car inflow",
                                backgroundColor: "red",
                                data: data.y[0]
                            },
                            {
                                label: "Car Out Flow",
                                backgroundColor: "blue",
                                data: data.y[1]
                            },
                            {
                                label: "Bike In Flow",
                                backgroundColor: "green",
                                data: data.y[2]
                            },
                            {
                                label: "Bike Out Flow",
                                backgroundColor: "orange",
                                data: data.y[3]
                            },
                            {
                                label: "Truck In Flow",
                                backgroundColor: "brown",
                                data: data.y[4]
                            },
                            {
                                label: "Truck Out Flow",
                                backgroundColor: "black",
                                data: data.y[5]
                            },
                        ]
                    };
                    myBarChart.update();

                });
            },330 * 1000
        )
            ;
        }
    </script>
{% endblock %}

Algorithm/templates/algorithm/list_Video.html
{% extends 'theme/admin/base.html' %}
{% block content_wrapper %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">
                <br>

                <a href="{% url 'get_video_input' %}" class="btn btn-primary pull-right"> Add Video</a>
                <br>

                <h3 align="center">Video List</h3>

            </div>
            <div class="table-responsive">
                <table class="table table-bordered table-striped table-hover dataTable container-fluid" id="myTable">
                    <thead>
                    <tr>
                        <th>Sno</th>
                        <th>File</th>
                        <th>Ip link</th>
                        <th>start x</th>
                        <th>start y</th>
                        <th>end x</th>
                        <th>end y</th>
                        <th>Processed</th>
                        <th> Created At</th>
                        <th> Actions</th>
                    </tr>
                    </thead>
                    {% for video in videos_list %}
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ video.file }}</td>
                            <td>{{ video.ip_link }}</td>
                            <td>{{ video.line_coord_init_x }}</td>
                            <td>{{ video.line_coord_init_y }}</td>
                            <td>{{ video.line_coord_end_x }}</td>
                            <td>{{ video.line_coord_end_y }}</td>
                            <td>{{ video.processed }}</td>
                            <td>{{ video.created_at }}</td>
                            <td>
                                <a href="{% url 'start_processing' video.id %}">
                                    <span class="glyphicon glyphicon-star">Start Processing</span>
                                </a>
                                <br>
                                <br>
                                <a href="{% url 'delete_video' video.id %}">
                                    <span class="glyphicon glyphicon-trash">Delete</span>
                                </a>
                                <br>
                                <br>
                                <a href="{% url 'output_process' video.id 0 %}">
                                    <span class="glyphicon glyphicon-eye-open">View Count Graph</span>
                                </a>
                                <br>
                                <br>
                                <a href="{% url 'output_process' video.id 1 %}">
                                    <span class="glyphicon glyphicon-eye-open">View Moving Average Graph</span>
                                </a>
                                <br>
                                <br>
                                <a href="{% url 'graph_output_video' video.id %}">
                                    <span class="glyphicon glyphicon-eye-open">View Moving Average Bar Graph</span>
                                </a>
                                <br>
                                <br>
                                <a href="{% url 'stop_process' video.id %}">
                                    <span class="glyphicon glyphicon-stop">Stop Processing</span>
                                </a>


                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
        </div>
    </div>
{% endblock %}

Algorithm/templates/algorithm/template.html
{% extends 'theme/admin/base.html' %}
{% block body %}
    <body class="hold-transition skin-blue fixed" onload="init()">
{% endblock %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% block headscript %}
<script>
    function init() {
        canvas = document.getElementById('can');
        ctx = canvas.getContext("2d");
        base_image = new Image();
        base_image.src = '{{ image_url }}';
        base_image.onload = function () {
            ctx.drawImage(base_image, 0, 0, 900, 600);
        };
        canvas.width = 900;
        canvas.height = 600;
        w = canvas.width;
        h = canvas.height;
        currX = 0;
        currY = 0;
        x = "red";
        y = 2;
        flag = false;
        {% if line_coordinates %}
            draw_line_custom({{ line_coordinates.0 }}, {{ line_coordinates.1 }}, {{ line_coordinates.2 }}, {{ line_coordinates.3 }});
        {% endif %}
        canvas.addEventListener("mousemove", function (e) {
            findxy('move', e)
        }, false);
        canvas.addEventListener("mousedown", function (e) {
            findxy('down', e)
        }, false);
        canvas.addEventListener("mouseup", function (e) {
            findxy('up', e)
        }, false);
        canvas.addEventListener("mouseout", function (e) {
            findxy('out', e)
        }, false);

    }

    function draw() {
        ctx.beginPath();
        ctx.moveTo(prevX, prevY);
        ctx.lineTo(currX, currY);
        ctx.strokeStyle = x;
        ctx.lineWidth = y;
        ctx.stroke();
        ctx.closePath();
    }

    function erase() {
        var m = confirm("Want to clear");
        if (m) {
            location.reload();
        }
    }

    function save() {
        form = document.getElementById("co_ords_form");
        input = document.getElementById("value");
        input.value = init_x + "|" + init_y + "/" + currX + "|" + currY;
        form.submit();
    }

    function draw_line() {
        ctx.beginPath();
        ctx.moveTo(init_x, init_y);
        ctx.lineTo(currX, currY);
        ctx.strokeStyle = x;
        ctx.lineWidth = y;
        ctx.stroke();
        ctx.closePath();
        console.log(init_x + "|" + init_y + "/" + currX + "|" + currY);
    }

    function draw_line_custom(init_x, init_y, currX, currY) {
        ctx.beginPath();
        ctx.moveTo(init_x, init_y);
        ctx.lineTo(currX, currY);
        ctx.strokeStyle = "red";
        ctx.lineWidth = 2;
        ctx.stroke();
        ctx.closePath();
    }

    function findxy(res, e) {
        if (res == 'down') {
            prevX = currX;
            prevY = currY;
            currX = e.clientX - canvas.offsetLeft;
            currY = e.clientY - canvas.offsetTop;

            flag = true;
            init_x = currX;
            init_y = currY;

        }
        if (res == 'up' || res == "out") {
            flag = false;
            draw_line();

        }
        if (res == 'move') {
            if (flag) {
                prevX = currX;
                prevY = currY;
                currX = e.clientX - canvas.offsetLeft;
                currY = e.clientY - canvas.offsetTop;

            }
        }
    }

</script>
    {% endblock %}
{% block content_wrapper %}
<canvas id="can" width="400" height="400" style="border:2px solid;"></canvas>
<input type="button" value="save" id="btn" size="30" onclick="save()">
<input type="button" value="clear" id="clr" size="23" onclick="erase()">
<form method="post" id="co_ords_form">
    {% csrf_token %}
    <input type="text" hidden id="path" name="path" value="{{ image_url }}">
    <input type="text" hidden id="value" name="value">
</form>
{% endblock %}

Algorithm/templates/algorithm/update.html
{% extends 'theme/admin/base.html' %}
{% load widget_tweaks %}
{% block content_wrapper %}
    <section class="wrapper">
        <div class="col-lg-12">
            <div class="panel panel-info">
                <div class="panel-heading"><h3 align="center">Update Form</h3></div>
                <div class="panel-body">
                    <form action="" method='post' role="form">
                        {% csrf_token %}
                        {% for field in form %}
                            <div class="form-group">
                                <label>{{ field.label }} <span class="required">*</span></label>
                                <div>
                                    {{ field |add_class:'form-control' }}
                                </div>
                            </div>
                        {% endfor %}
                        <input type="submit" class="btn btn-default" style="float: right">Submit</input>
                    </form>
                </div>
            </div>
        </div>
    </section>
{% endblock %}